ALTER TABLE agent_messages ADD COLUMN IF NOT EXISTS tokens_after INT;

ALTER TABLE agent_sessions
    ADD COLUMN IF NOT EXISTS context_tokens INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS context_window INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_input BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_output BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_reasoning BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_cache_read BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_model_calls INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_subagent_input BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_subagent_output BIGINT NOT NULL DEFAULT 0;
